In [9]:
# 1
import numpy as np
a = np.random.rand(10, 3)
print(a, '\n')
for string in a:
    tmp = 100
    for i in string:
        if abs(i - 0.5) < abs(tmp - 0.5):
            tmp = i
    print(tmp) 

[[0.53518908 0.01484446 0.9227161 ]
 [0.31713623 0.29977403 0.77454971]
 [0.73670288 0.15978546 0.20037171]
 [0.34285463 0.22323448 0.1506905 ]
 [0.62349298 0.958637   0.93407433]
 [0.36317492 0.70592402 0.17837016]
 [0.14426974 0.43160656 0.82707636]
 [0.75192183 0.85443452 0.47627729]
 [0.63798263 0.90914682 0.91960912]
 [0.6744545  0.45289611 0.86921937]] 

0.5351890812784043
0.31713623360150445
0.7367028830774887
0.34285462623768104
0.6234929795552313
0.36317492455870826
0.4316065635455598
0.4762772916327781
0.6379826336604596
0.45289610827085924


In [11]:
# 2
import numpy as np
a = np.random.rand(6,6)
print(a, '\n')
for i in range(6):
    print(a[i].sum() / a[:,i].min())

[[0.33254456 0.25046318 0.41379819 0.49658453 0.38313707 0.71379146]
 [0.17138726 0.19556042 0.44814447 0.14796888 0.10637734 0.05997172]
 [0.48232619 0.56335164 0.91991088 0.62843502 0.27590505 0.85055986]
 [0.59754482 0.64509479 0.96061722 0.88638516 0.17180028 0.1474762 ]
 [0.10810771 0.52498035 0.30934475 0.23501944 0.68899075 0.34216788]
 [0.85444045 0.30461322 0.3972838  0.39866657 0.56096097 0.98182886]] 

23.960539610331438
5.775249013546853
12.026997823449081
23.038076534478783
20.762041925123764
58.32405702392566


In [13]:
# 3
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max = 0
for i in range(0, len(x) - 1):
    if x[i + 1] == 0:
        if x[i] > max:
            max = x[i]
print(max)

7


In [12]:
# 4
import numpy as np
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j] += 1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [17]:
# K-means

import numpy.random 
from scipy.spatial import distance
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/sharmaroshan/Clustering-of-Mall-Customers/master/Mall_Customers.csv'
data = np.loadtxt(url, delimiter = ',', dtype = object, skiprows = 1)
data[:5] #CustomerID, Genre, Age, Annual Income (k$), Spending Score (1-100)

data[:, 1] = data[:, 1] == 'Male'
data = data.astype(float)
data[:5]

#take data in two-dimensional array
def DataArray(data): 
    mean = data.mean(axis=0)
    std = data.std(axis=0)
    return (data - mean) / std
Array_of_data = DataArray(data[:,2:])
print(Array_of_data[:7])

[[-1.42456879 -1.73899919 -0.43480148]
 [-1.28103541 -1.73899919  1.19570407]
 [-1.3528021  -1.70082976 -1.71591298]
 [-1.13750203 -1.70082976  1.04041783]
 [-0.56336851 -1.66266033 -0.39597992]
 [-1.20926872 -1.66266033  1.00159627]
 [-0.27630176 -1.62449091 -1.71591298]]


In [30]:
def Reassignment (tem, dat):
    data_1 = np.empty((len(dat),len(dat[0])))
    sh = distance.cdist(tem, dat, 'sqeuclidean') # shift from center
    temp = np.hstack((tem, sh.argmin(axis=1).reshape(len(sh),1)))
    for i in range(len(dat)):
        dat_1[i] = np.vstack(row for row in temp if row[- 1] == i).mean(axis = 0)[:-1]
        
    return data_1

def Kmeans(tem, k, iter = 20, eps = 1e-10):
    if type(k) == int:
        dat = tem[np.random.choice(range(len(tem)), k, False)]
    else:
        dat = k
    prev_sh = - 1
    fut_sh = distance.cdist(tem, dat, 'sqeuclidean').min(axis = 1).sum()
    while abs(fut_sh - prev_sh) > eps:
        dat = Reassigment (tem, dat)
        prev_distortion = fut_sh
        cur_distortion = distance.cdist(tem, dat, 'sqeuclidean').min(axis = 1).sum()
        
    return dat, fut_sh  

dat, shift = kmeans(Array_of_data[:,[1,2]], 5)

NameError: name 'obs' is not defined